### ISSUE TITLE
netu resolver

### ISSUE THREAD

**Issue by LordVenom** [kodi-czsk/script.module.stream.resolver#1]
Hello,

I want use netu resolver. It's possible. It works ?

**Comment by lubo** [comment]
netu.tv is now hqq.tv. I have fixed hqq resolver in 7ee8819ac65bd09aa77186849351e3dc07a742bb and merged netu and hqq resolvers in db69f764083d25e74c07d1785a70e3e395748e7f. It should work again in version 1.6.25.

**Comment by lubo** [comment]
@lzoubek I propose closing this issue since it has become outdated as of db69f764083d25e74c07d1785a70e3e395748e7f.
