### ISSUE TITLE
Queue item

### ISSUE THREAD

**Issue by KOPRajs** [kodi-czsk/script.module.stream.resolver#27]
Hi,
please consider adding "Queue item" action to context menus for videos. It appends the video to the current playlist. It shouldn't break anything and it would be very useful for many of the addons.

This works for me:

```
$ diff -u xbmcutil.xx xbmcutil.py 
--- xbmcutil.xx 1970-01-01 01:00:00.000000000 +0100
+++ xbmcutil.py 1970-01-01 01:00:00.000000000 +0100
@@ -116,6 +116,7 @@
     li.setInfo( type='Video', infoLabels=infoLabels )
     li.setProperty('IsPlayable','true')
     items = []
+    items.append((xbmc.getLocalizedString(13347),'Action(Queue)'))
     for mi in menuItems.keys():
         action = menuItems[mi]
         if not type(action) == type({}):
```

**Comment by lubo** [comment]
Hello, @KOPRajs. If it works for you, then consider making a pull request, please.

**Comment by lubo** [comment]
Pridane v 2ccedd97a2a9d5fb07328c0758ea7d2ae6591315. Tato zmena bude zahrnuta v dalsej verzii.
