### ISSUE TITLE
titulky stále nejdou

### ISSUE THREAD

**Issue by Veisen** [kodi-czsk/script.module.stream.resolver#48]
titulky jdou každé 10-20 načtení

**Comment by pstruh** [comment]
Titulky nenatiahne z Kniznice ani z doplnku v Kodi 17. Nakolko je to stale BETA neviem ci sa to bude riesit :)
RPi2 Kodi 17 RC3 LibreELEC v7.95.1
Win10 Kodi 17 RC3
Sosac 1.3.0

**Comment by lubo** [comment]
Pretrvava tento problem i nadalej ?

**Comment by pstruh** [comment]
ano problem len v kodi 17,  kodi 16 je ok.
