### ISSUE TITLE
openload - nefunguje

### ISSUE THREAD

**Issue by bbaronSVK** [kodi-czsk/script.module.stream.resolver#55]
openload resolver prestal fungovat. Ak by mal niekto cas to opravit:
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/hosters/openload.py
bol by som celkom vdacny

**Comment by jose1711** [comment]
s akym addonom to pouzivas?

**Comment by bbaronSVK** [comment]
skusal som to so svojim pluginom, ktory je vo vyvoji. Link som pouzil [tento](https://openload.co/embed/lub_vlMcNvw/Arrival.2016.720p.WEB-DL.950MB.MkvCage.www.RapidMovieZ.com.mkv.mp4) Na webe to funguje, ale neresolvne mi ho.

**Comment by jose1711** [comment]
skus pozriet topserialy addon, pouzivaju urlresolver, ktory je celkom casto aktualizovany

**Comment by bbaronSVK** [comment]
ano, oni pouzivaju urlresolver a nie cz sk resolver. chcel som pouzit nieco, co je v "nasom" repozitary.

**Comment by bbaronSVK** [comment]
ok, urlresolver sa zda byt jednoduchy na pouzitie...skusim to s nim...dik
