### ISSUE TITLE
Kodi 17 - SimpleJSON

### ISSUE THREAD

**Issue by ghost** [kodi-czsk/script.module.stream.resolver#56]
Ahoj, prosím, můžete mrknou na chybu s importem simplejson? Po aktualizaci na novo verzi nefunguje import simplejson. 
 Děkuji

**Comment by lubo** [comment]
Reinstaloval si si pluginy ?

**Comment by ghost** [comment]
Ahoj, ano, odinstaloval jsem doplnek sosace i vsechny z z tohoto repozitare, restartoval a a znovu nahral. A stale byla chya ze nenasel simplejson. Kdyz zmenim import simplejson as json jen na import json ve vsech py scriptech tak to bezi. Mam to zkusit jeste i jinak?

**Comment by lubo** [comment]
A odinstaloval si si aj script.module.stream.resolver ?

**Comment by ghost** [comment]
Myslel jsem, ze se odebere kdyz odeberu repozitar. Je nejaka moznost jak ho odinstalovat z gui?
