### ISSUE TITLE
How to import this module.

### ISSUE THREAD

**Issue by b-sridhar** [kodi-czsk/script.module.stream.resolver#61]
Hi,
Sorry for the noob question. I have been trying to import this module in a plugin and keep receiving `ImportError: No module named <ModuleName>`.  I have tried `stream.resolver`, `resolver` for `ModuleName`. Could you please let me know how to use this in a module? It would be great if you can add an example to show how to use the module.

**Comment by jose1711** [comment]
hello,
multiple addons at https://github.com/kodi-czsk/repository make use of this module - i suggest you take an inspiration there. this should get you going though:

* ```<import addon="script.module.stream.resolver" version="1.6.31" />``` in your ```<requires>``` of your ```addon.xml```
* ```import resolver```
